Repository plonegovbr/brasil.gov.portal, pull requests merged in 2018-09, with the labels that each got.

#519 Novos estilos para o cover
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/profiles/default/registry.xml
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_addons_settings.py
  src/brasil/gov/portal/upgrades/configure.zcml
  src/brasil/gov/portal/upgrades/v10902/__init__.py
  src/brasil/gov/portal/upgrades/v10902/configure.zcml
  src/brasil/gov/portal/upgrades/v10902/profile/registry.xml
Labels: 2.x, in progress

#521 Remove background image validator
  CHANGES.rst
  src/brasil/gov/portal/controlpanel/portal.py
  src/brasil/gov/portal/tests/test_utils.py
  src/brasil/gov/portal/utils.py
Labels: 2.x, ready

#517 Define tamanho de imagens para o IDG
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/propertiestool.xml
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10902/configure.zcml
  src/brasil/gov/portal/upgrades/v10902/profile/propertiestool.xml
Labels: 2.x, in progress

#522 Update i18n
  CHANGES.rst
  src/brasil/gov/portal/locales/brasil.gov.portal.pot
  src/brasil/gov/portal/locales/es/LC_MESSAGES/brasil.gov.portal.po
  src/brasil/gov/portal/locales/es/LC_MESSAGES/plone.po
  src/brasil/gov/portal/locales/plone.pot
  src/brasil/gov/portal/locales/pt_BR/LC_MESSAGES/brasil.gov.portal.po
  src/brasil/gov/portal/locales/pt_BR/LC_MESSAGES/plone.po
Labels: 2.x, in progress

#530 Install webcouturier.dropdownmenu on upgrade step
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/configure.zcml
  src/brasil/gov/portal/upgrades/v10903/__init__.py
  src/brasil/gov/portal/upgrades/v10903/configure.zcml
Labels: 2.x, ready

#532 Fix dropdown_depth
  src/brasil/gov/portal/profiles/default/propertiestool.xml
  src/brasil/gov/portal/tests/test_portal_properties.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10903/profile/propertiestool.xml
Labels: 2.x

#534 Fix collective.cover tile styles
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/profiles/default/registry.xml
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_addons_settings.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/configure.zcml
  src/brasil/gov/portal/upgrades/v10901/profile/registry.xml
  src/brasil/gov/portal/upgrades/v10904/__init__.py
  src/brasil/gov/portal/upgrades/v10904/configure.zcml
  src/brasil/gov/portal/upgrades/v10904/profile/registry.xml
Labels: 2.x

#538 Rodfersou/add tip preview
  CHANGES.rst
  src/brasil/gov/portal/browser/plone/overrides/Products.TinyMCE.skins.tinymce.plugins.plonebrowser.js.plonebrowser.js
  src/brasil/gov/portal/browser/plone/overrides/Products.TinyMCE.skins.tinymce.plugins.plonebrowser.plonebrowser.htm.pt
  webpack/app/brasilgovportal.js
  webpack/app/brasilgovportal.scss
  webpack/app/img/preview.png
  webpack/app/js/tippreview.js
  webpack/app/resources.pt
  webpack/app/scss/_tippreview.scss
  webpack/package.json
  webpack/webpack.config.js
Labels: ready
