Repository plonegovbr/brasil.gov.portal, pull requests merged in 2018-07, with the labels that each got.

#491 Fix AttributeError on upgrade step v10900
  CHANGES.rst
  src/brasil/gov/portal/upgrades/v10900/__init__.py
Labels: 2.x

#492 Fix profile version
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/tests/test_setup.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10900/profile/rolemap.xml
Labels: 2.x

#493 Remove portlet assigments at portal root
  .gitattributes
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/configure.zcml
  src/brasil/gov/portal/upgrades/v10901/__init__.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
Labels: 2.x, enhancement

#494 Fix column widths on cover objects based on new layout
  CHANGES.rst
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10901/__init__.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
Labels: 2.x

#497 Remove "destaques" viewlet and direct dependency on five.grok
  CHANGES.rst
  setup.py
  src/brasil/gov/portal/browser/viewlets/destaques.py
  src/brasil/gov/portal/browser/viewlets/templates/destaques_viewlet.pt
  src/brasil/gov/portal/configure.zcml
  src/brasil/gov/portal/static/js/main.js
  src/brasil/gov/portal/tests/test_viewlets.py
Labels: 2.x, enhancement, ready

#498 Novas configurações do cover
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/registry.xml
  src/brasil/gov/portal/tests/test_addons_settings.py
Labels: 2.x, enhancement, ready

#499 Review infographic workflow
  CHANGES.rst
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_setup.py
Labels: 2.x, bug, ready

#500 Adiciona https nas urls das redes sociais
  CHANGES.rst
  src/brasil/gov/portal/config.py
Labels: 2.x, enhancement, ready
