Repository plonegovbr/brasil.gov.portal, pull requests merged in 2018-08, with the labels that each got.

#503 Do not hide brasil.gov.portlets profiles in the policy package
  setup.py
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_setup.py
Labels: 2.x, in progress

#505 Add upgrade step do update collective.cover default settings
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
  src/brasil/gov/portal/upgrades/v10901/profile/registry.xml
Labels: 2.x, enhancement, ready

#507 Add header options to portal-settings configlet
  CHANGES.rst
  src/brasil/gov/portal/browser/busca/__init__.py
  src/brasil/gov/portal/browser/busca/configure.zcml
  src/brasil/gov/portal/browser/busca/search.pt
  src/brasil/gov/portal/browser/busca/searchbox.pt
  src/brasil/gov/portal/browser/busca/searchbox.py
  src/brasil/gov/portal/browser/busca/updated_search.pt
  src/brasil/gov/portal/browser/configure.zcml
  src/brasil/gov/portal/browser/helper.py
  src/brasil/gov/portal/browser/viewlets/configure.zcml
  src/brasil/gov/portal/browser/viewlets/templates/searchbox.pt
  src/brasil/gov/portal/controlpanel/portal.py
  src/brasil/gov/portal/profiles/default/controlpanel.xml
  src/brasil/gov/portal/static/js/main.js
  src/brasil/gov/portal/tests/test_controlpanel_portal.py
  src/brasil/gov/portal/tests/test_helper_view.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/tests/test_utils.py
  src/brasil/gov/portal/tests/test_viewlets.py
  src/brasil/gov/portal/upgrades/__init__.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
  src/brasil/gov/portal/upgrades/v10901/profile/controlpanel.xml
  src/brasil/gov/portal/upgrades/v10901/profile/registry.xml
  src/brasil/gov/portal/utils.py
Labels: 2.x, enhancement, in progress

#508 Remove dependency on plone.directives.form
  CHANGES.rst
  setup.py
  src/brasil/gov/portal/content/audio_file.py
Labels: 2.x, enhancement, ready

#512 Add Content Central View
  CHANGES.rst
  src/brasil/gov/portal/browser/content/configure.zcml
  src/brasil/gov/portal/browser/content/contentcentral.py
  src/brasil/gov/portal/browser/content/templates/contentcentral.pt
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_contentcentral_view.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10901/__init__.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
Labels: 2.x, ready

#514 Do no install deprecated news article tile
  src/brasil/gov/portal/profiles/default/registry.xml
  src/brasil/gov/portal/tests/test_addons_settings.py
Labels: 2.x

#510 Uninstall Products.Doormat
  CHANGES.rst
  setup.py
  src/brasil/gov/portal/browser/content/configure.zcml
  src/brasil/gov/portal/browser/content/doormat.py
  src/brasil/gov/portal/browser/content/templates/doormat_bare_view.pt
  src/brasil/gov/portal/browser/content/templates/doormat_view.pt
  src/brasil/gov/portal/dependencies.zcml
  src/brasil/gov/portal/profiles/default/metadata.xml
  src/brasil/gov/portal/profiles/default/propertiestool.xml
  src/brasil/gov/portal/profiles/default/types/Doormat.xml
  src/brasil/gov/portal/profiles/default/types/DoormatCollection.xml
  src/brasil/gov/portal/profiles/default/types/DoormatSection.xml
  src/brasil/gov/portal/profiles/default/viewlets.xml
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/testing.py
  src/brasil/gov/portal/tests/test_init_content.py
  src/brasil/gov/portal/tests/test_setup.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10901/__init__.py
  src/brasil/gov/portal/upgrades/v10901/configure.zcml
  src/brasil/gov/portal/upgrades/v10901/profile/viewlets.xml
Labels: 2.x, enhancement, help wanted, in progress

#513 Fix upgrade step
  src/brasil/gov/portal/setuphandlers.py
  src/brasil/gov/portal/tests/test_upgrades.py
  src/brasil/gov/portal/upgrades/v10901/__init__.py
Labels: 2.x, in progress

#516 Fixed encode error when insert an item
  CHANGES.rst
  src/brasil/gov/portal/controlpanel/portalservices.py
  src/brasil/gov/portal/tests/robot/test_portal_services.robot
Labels: 2.x

#518 Remove references to deprecated tiles
  CHANGES.rst
  src/brasil/gov/portal/profiles/default/registry.xml
  src/brasil/gov/portal/tests/test_addons_settings.py
Labels: 2.x
